# Generated by Django 2.2.6 on 2019-10-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=30)),
                ('url', models.TextField(max_length=256)),
                ('userName', models.TextField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=50)),
                ('schedule', models.CharField(max_length=50)),
                ('messageFail', models.BooleanField(default=False)),
                ('messageSuccess', models.BooleanField(default=False)),
                ('messageTooMuchFailures', models.BooleanField(default=False)),
                ('saveAnswer', models.BooleanField(default=False)),
            ],
        ),
    ]
